baseURL = 'https://dermatologiediest.be/'
languageCode = 'be-nl'
title = 'Dermatologie Diest'
theme = ['github.com/olbrew/hugo-hero-theme']
[module]
    [[module.imports]]
        path = 'github.com/olbrew/hugo-hero-theme'

[params.homepage_meta_tags]
    meta_description = "a description of your website."
    meta_og_title = "Dermatologie Diest"
    meta_og_type = "website"
    meta_og_url = "https://www.dermatologiediest.be"
    meta_og_image = "https://www.mywebsite.com/images/tn.png"
    meta_og_description = "a description of your website."
    meta_twitter_creator = "@olbrew"
