#baseURL: https://dermatologiediest.be
baseURL: https://dermatologiediest.com
languageCode: be-nl
title: Dermatologie Diest

module:
  imports:
    path: github.com/olbrew/hugo-hero-theme

params:
  google_analytics_id: ""

  logo:
    mobile: logo-mobile.png
    mobile_height: 36px
    mobile_width: 36px
    desktop: logo-desktop.png
    desktop_height: 30px
    desktop_width: 250px
    alt: Dermatologie Diest

  homepage_meta_tags:
    meta_description: Dagmar Coninx is een dermatoloog in Diest
    meta_og_title: Dermatologie Diest
    meta_og_type: website
    meta_og_url: https://www.dermatologiediest.be
    meta_og_image: https://www.dermatologiediest.be/img/gebouw.jpg
    meta_og_description: Dagmar Coninx is een dermatoloog in Diest
    meta_twitter_card: summary
    meta_twitter_creator: '@olbrew'

menu:
  main:
    - name: Contact
      url: '#contact'
      weight: 1
    - name: Over mij
      url: '#about'
      weight: 2
    - name: Diensten
      url: '#services'
      weight: 3
    - name: Boek Afspraak
      url: '#book'
      weight: 4
permalinks:
  post: /:year/:month/:day/:slug/
  pages: /:filename/
